export const characters = {
  allan: require("./images/characters/picker/premium/Bitcoin_Allan.png"),
  booena: require("./images/characters/picker/premium/Booena.png"),
  cryptobro: require("./images/characters/picker/Crypto_Bro.png"),
  dadgpt: require("./images/characters/picker/Dad_GPT.png"),
  drwrong: require("./images/characters/picker/premium/Dr_Wrong.png"),
  dubai: require("./images/characters/picker/Dubai_Princess.png"),
  goodtime: require("./images/characters/picker/premium/Mr_GoodTime.png"),
  hangreta: require("./images/characters/picker/premium/Hangreta.png"),
  monday: require("./images/characters/picker/premium/Monday.png"),
  pete: require("./images/characters/picker/PluggedIn_Pete.png"),
  retrograda: require("./images/characters/picker/Retrograda.png"),
  screena: require("./images/characters/picker/premium/Screena.png"),
  simpalot: require("./images/characters/picker/Sir_Simpalot.png"),
  susie: require("./images/characters/picker/Remote_Susie.png"),
  tedimechov: require("./images/characters/picker/premium/Tedimechov.png"),
  vanessa: require("./images/characters/picker/Silent_Vanessa.png"),
  vape: require("./images/characters/picker/Uncle_Vape.png"),
  // vibeswitch: require("./images/characters/picker/premium/Vibeswitch.png"),
  virala: require("./images/characters/picker/Virala.png"),
  winebender: require("./images/characters/picker/premium/Wine_Bender.png"),
  morgrossman: require("./images/characters/picker/premium/MorGrossman.png"),
  cheffranco: require("./images/characters/picker/premium/Chef_Franco.png"),
  xglitch: require("./images/characters/picker/premium/xqc.png"),
};

export const characters_wonRound = {
  allan: require("./images/characters/wonRound/Bitcoin_Allan-W.png"),
  booena: require("./images/characters/wonRound/Booena-W3.png"),
  franco: require("./images/characters/wonRound/Chef_franco-W.png"),
  brochain: require("./images/characters/wonRound/Crypto_bro-W2.png"),
  dad_gpt: require("./images/characters/wonRound/Dad_GPT-W.png"),
  dr_wrong: require("./images/characters/wonRound/DrWrong-W2.png"),
  dubai: require("./images/characters/wonRound/DuBai-W.png"),
  hangreta: require("./images/characters/wonRound/Hangreta-W.png"),
  monday: require("./images/characters/wonRound/monday-W.png"),
  mr_good_time: require("./images/characters/wonRound/Mr_GoodTime-W.png"),
  pete: require("./images/characters/wonRound/PluggedIn_pete-W2.png"),
  susie: require("./images/characters/wonRound/RemoteSusie-W.png"),
  retrograda: require("./images/characters/wonRound/Retrograda-W.png"),
  screena: require("./images/characters/wonRound/screena-W.png"),
  vanessa: require("./images/characters/wonRound/SilentVanessa-W.png"),
  simpalot: require("./images/characters/wonRound/Sir_Simpalot-W2.png"),
  tedimechov: require("./images/characters/wonRound/Tedimechov-W.png"),
  uncle_vape: require("./images/characters/wonRound/UncleVape-W2.png"),
  virala: require("./images/characters/wonRound/Virala-W.png"),
  winebender: require("./images/characters/wonRound/WineBender_W.png"),
};
export const characters_lostRound = {
  allan: require("./images/characters/lostRound/Bitcoin_allan-L.png"),
  booena: require("./images/characters/lostRound/Booena-L2.png"),
  franco: require("./images/characters/lostRound/Chef_franco-L.png"),
  brochain: require("./images/characters/lostRound/Cryp_bro-L.png"),
  dad_gpt: require("./images/characters/lostRound/DAD_Gpt-L.png"),
  dr_wrong: require("./images/characters/lostRound/DrWrong-L.png"),
  dubai: require("./images/characters/lostRound/DuBai-L.png"),
  hangreta: require("./images/characters/lostRound/Hangreta-L.png"),
  monday: require("./images/characters/lostRound/Monday-L3.png"),
  mr_good_time: require("./images/characters/lostRound/Mr_GoodTime-L.png"),
  pete: require("./images/characters/lostRound/PluggedIn_Pete-L2.png"),
  susie: require("./images/characters/lostRound/Remote_Susie-L.png"),
  retrograda: require("./images/characters/lostRound/Retrograda-L2.png"),
  screena: require("./images/characters/lostRound/screena-L.png"),
  vanessa: require("./images/characters/lostRound/SilentVanessa-L2.png"),
  simpalot: require("./images/characters/lostRound/Simpalot-L.png"),
  tedimechov: require("./images/characters/lostRound/Tedimechov-L.png"),
  uncle_vape: require("./images/characters/lostRound/UncleVape-L.png"),
  virala: require("./images/characters/lostRound/Virala-L.png"),
  winebender: require("./images/characters/lostRound/WineBender-L.png"),
};
export const characters_loss = {
  allan: require("./images/characters/lost_images/premium/BitcoinAllan-L.png"),
  booena: require("./images/characters/lost_images/premium/Booena-L.png"),
  cryptobro: require("./images/characters/lost_images/free/BroChain-L.png"),
  dadgpt: require("./images/characters/lost_images/free/DadGPT-L.png"),
  drwrong: require("./images/characters/lost_images/premium/DrWrong-L.png"),
  dubai: require("./images/characters/lost_images/free/PrincessDubai-L.png"),
  goodtime: require("./images/characters/lost_images/premium/MrGoodTime-L.png"),
  hangreta: require("./images/characters/lost_images/premium/Hangreta-L.png"),
  monday: require("./images/characters/lost_images/premium/Monday-L.png"),
  pete: require("./images/characters/lost_images/free/PluggedInPete-L.png"),
  retrograda: require("./images/characters/lost_images/free/Retrograda-L.png"),
  screena: require("./images/characters/lost_images/premium/Screena-L.png"),
  simpalot: require("./images/characters/lost_images/SirSimpalot-L.png"),
  susie: require("./images/characters/lost_images/free/RemoteSusie-L.png"),
  tedimechov: require("./images/characters/lost_images/premium/Tedimechov-L.png"),
  vanessa: require("./images/characters/lost_images/free/SilentVanessa-L.png"),
  vape: require("./images/characters/lost_images/UncleVape-L.png"),
  virala: require("./images/characters/lost_images/free/Virala-L.png"),
  winebender: require("./images/characters/lost_images/premium/WineBender-L.png"),
  xglitch: require("./images/characters/lost_images/premium/XGlitch-L.png"),
};

export const characters_win = {
  allan: require("./images/characters/win_images/premium/BitcoinAllan-W(2).png"),
  booena: require("./images/characters/win_images/premium/Booena-W.png"),
  cryptobro: require("./images/characters/win_images/free/BroChain-W.png"),
  dadgpt: require("./images/characters/win_images/free/DadGPT-W.png"),
  drwrong: require("./images/characters/win_images/premium/DrWrong-W.png"),
  dubai: require("./images/characters/win_images/free/DubaiPrincess-W.png"),
  goodtime: require("./images/characters/win_images/premium/MrGoodTime-W.png"),
  hangreta: require("./images/characters/win_images/premium/Hangreta-W.png"),
  monday: require("./images/characters/win_images/premium/Monday-W(2).png"),
  pete: require("./images/characters/win_images/free/PluggedInPete-W.png"),
  retrograda: require("./images/characters/win_images/free/Retrograda-W.png"),
  screena: require("./images/characters/win_images/premium/Screena-W.png"),
  simpalot: require("./images/characters/win_images/free/SirSimpalot-W.png"),
  susie: require("./images/characters/win_images/free/RemoteSusie-W.png"),
  tedimechov: require("./images/characters/win_images/premium/Tedimechov-W.png"),
  vanessa: require("./images/characters/win_images/free/SilentVanessa-W.png"),
  vape: require("./images/characters/win_images/free/UncleVape-W.png"),
  virala: require("./images/characters/win_images/free/Virala-W.png"),
  winebender: require("./images/characters/win_images/premium/WineBender-W.png"),
  xglitch: require("./images/characters/win_images/premium/XGlitch-W.png"),
};

export const character_avatars = {
  abu_dubaiena: require("./images/characters/avatars/Dubai_Princess.png"),
  bitcoin_allan: require("./images/characters/avatars/bitcoin_allan.png"),
  booena: require("./images/characters/avatars/Booena.png"),
  brochain: require("./images/characters/avatars/Crypto_bro.png"),
  chef_franco: require("./images/characters/avatars/chef_franco.png"),
  dad_gpt: require("./images/characters/avatars/dad_gpt.png"),
  dr_wrong: require("./images/characters/avatars/drwrong.png"),
  hangreta: require("./images/characters/avatars/hangreta.png"),
  monday: require("./images/characters/avatars/monday.png"),
  mr_good_time: require("./images/characters/avatars/mr_good_time.png"),
  plugged_in_pete: require("./images/characters/avatars/Pluggedin_pete.png"),
  remote_susie: require("./images/characters/avatars/Remote_susie.png"),
  retrograda: require("./images/characters/avatars/Retrograda.png"),
  screena: require("./images/characters/avatars/screena.png"),
  silent_vanessa: require("./images/characters/avatars/Silent_Vanessa.png"),
  sir_simpalot: require("./images/characters/avatars/Sir_Simpalot.png"),
  tedimechov: require("./images/characters/avatars/tedimechov.png"),
  uncle_vape: require("./images/characters/avatars/Uncle_Vape.png"),
  // vibeswitch: require("./images/characters/avatars/vibeswitch.png"),
  virala: require("./images/characters/avatars/virala.png"),
  wine_bender: require("./images/characters/avatars/wine_bender.png"),
  xglitch: require("./images/characters/avatars/xglitch.png"),
} as const;

export const character_videos = {
  booena: require("./images/characters/win_images/premium/Booena-W.mp4"),
  brochain: require("./images/characters/win_images/free/BroChain-W.mp4"),
  dadgpt: require("./images/characters/win_images/free/DadGPT-W.mp4"),
  mrGoodTime: require("./images/characters/win_images/premium/MrGoodTime-W.mp4"),
  monday: require("./images/characters/win_images/premium/Monday-W(2).mp4"),
  retrograda: require("./images/characters/win_images/free/Retrograda-W.mp4"),
  tedimechov: require("./images/characters/win_images/premium/Tedimechov-W.mp4"),
  virala: require("./images/characters/win_images/free/Virala-W.mp4"),
  xglitch: require("./images/characters/win_images/premium/XGlitch-W.mp4"),
  allanL: require("./images/characters/lost_images/premium/BitcoinAllan-L.mp4"),
  booenaL: require("./images/characters/lost_images/premium/Booena-L.mp4"),
  mondayL: require("./images/characters/lost_images/premium/Monday-L.mp4"),
  winebenderL: require("./images/characters/lost_images/premium/WineBender-L.mp4"),
  xglitchL: require("./images/characters/lost_images/premium/XGlitch-L.mp4"),
  brochainL: require("./images/characters/lost_images/free/BroChain-L.mp4"),
  dadgptL: require("./images/characters/lost_images/free/DadGPT-L.mp4"),
  retrogradaL: require("./images/characters/lost_images/free/Retrograda-L.mp4"),
  viralaL: require("./images/characters/lost_images/free/Virala-L.mp4"),
};

export const character_standings = {
  allan: require("./images/characters/frames/premium/bitcoin-allan.png"),
  booena: require("./images/characters/frames/premium/booena.png"),
  brochain: require("./images/characters/frames/free/crypto-bro.png"),
  dadgpt: require("./images/characters/frames/free/dad-gpt.png"),
  pluggedInPete: require("./images/characters/frames/free/plugged-in-pete.png"),
  susie: require("./images/characters/frames/free/remote-susie.png"),
  vanessa: require("./images/characters/frames/free/silent-vanessa.png"),
  sirSimpalot: require("./images/characters/frames/free/sir-simpalot.png"),
  uncleVape: require("./images/characters/frames/free/uncle-vape.png"),
  virala: require("./images/characters/frames/free/virala.png"),
  mrGoodTime: require("./images/characters/frames/premium/mr-good-time.png"),
  monday: require("./images/characters/frames/premium/monday.png"),
  drWrong: require("./images/characters/frames/premium/dr-wrong.png"),
  hangreta: require("./images/characters/frames/premium/hangreta.png"),
  screena: require("./images/characters/frames/premium/screena.png"),
  tedimechov: require("./images/characters/frames/premium/tedimechov.png"),
  winebender: require("./images/characters/frames/premium/winebender.png"),
  xglitch: require("./images/characters/frames/premium/xglitch.png"),
  retrograda: require("./images/characters/frames/free/retrograda.png"),
  abu_dubaiena: require("./images/characters/frames/free/dubai.png"),
};

export const character_standing_backgrounds = {
  allan: require("./images/characters/frames/premium/backgrounds/allan.png"),
  booena: require("./images/characters/frames/premium/backgrounds/booena.png"),
  mrGoodTime: require("./images/characters/frames/premium/backgrounds/mrGoodTime.png"),
  monday: require("./images/characters/frames/premium/backgrounds/monday.png"),
  drWrong: require("./images/characters/frames/premium/backgrounds/drwrong.png"),
  hangreta: require("./images/characters/frames/premium/backgrounds/hangreta.png"),
  screena: require("./images/characters/frames/premium/backgrounds/screena.png"),
  tedimechov: require("./images/characters/frames/premium/backgrounds/tedimechov.png"),
  xglitch: require("./images/characters/frames/premium/backgrounds/xglitch.png"),
  winebender: require("./images/characters/frames/premium/backgrounds/winebender.png"),
};

export type AvatarId = keyof typeof character_avatars;
