export const images = {
  curtainTop: require("./images/curtainTop.png"),
  curtainBottom: require("./images/curtainBottom.png"),
  loader: require("./images/loader.png"),
  googleIcon: require("./images/googleIcon.png"),
};

export const game_images = {
  passDevice: require("./images/game/HandThePhone.png"),
  logoMusicOn: require("./images/game/logoMusicOn.png"),
  logoMusicOff: require("./images/game/logoMusicOff.png"),
  logoFrMusicOn: require("./images/game/logoFrMusicOn.png"),
  logoFrMusicOff: require("./images/game/logoFrMusicOff.png"),
  logoEsMusicOn: require("./images/game/logoEsMusicOn.png"),
  logoEsMusicOff: require("./images/game/logoEsMusicOff.png"),
  logoBgMusicOn: require("./images/game/logoBgMusicOn.png"),
  logoBgMusicOff: require("./images/game/logoBgMusicOff.png"),
  settingsIcon: require("./images/game/settingsIcon.png"),
  userIcon: require("./images/game/userIcon.png"),
  storeBtn: require("./images/game/storeBtn.png"),
  howToPlayBtn: require("./images/game/howToPlayBtn.png"),
  bgHtpBtn: require("./images/game/bgButton.png"),
  bgStoreBtn: require("./images/game/bgButtonPurple.png"),
  bgPlayBtn: require("./images/game/bgButtonRed.png"),
  storeIcon: require("./images/game/storeIcon.png"),
  htpIcon: require("./images/game/htpIcon.png"),
  btnMinus: require("./images/game/btnMinus.png"),
  btnPlus: require("./images/game/btnPlus.png"),
  pplCountContainer: require("./images/game/calcPpl.png"),
  leftArrow: require("./images/game/arrowLeft.png"),
  rightArrow: require("./images/game/arrowRight.png"),
  heroNameContainer: require("./images/game/heroNameContainer.png"),
  heroPickerBottom: require("./images/game/HeroPickerBottom.png"),
  lock: require("./images/game/lock01.png"),
  lock2: require("./images/game/lock02.png"),
  lock3: require("./images/game/lock03.png"),
  lock4: require("./images/game/lock04.png"),
  lock5: require("./images/game/lock05.png"),
  arrowRightVote: require("./images/game/arrowRightVote.png"),
  arrowRightVote2: require("./images/game/arrowRightVote2.png"),
  arrowRightVote3: require("./images/game/arrowRightVote3.png"),
  arrowRightVote4: require("./images/game/arrowRightVote4.png"),
  timer: require("./images/game/timerNew.png"),
  readyToVote: require("./images/game/readyToVote.png"),
  lostRound: require("./images/game/lostRoundQuestion.png"),
  lostRoundQuestion: require("./images/game/lostRoundQ.png"),
  wonRoundQuestion: require("./images/game/wonRoundQ.png"),
  wonRound: require("./images/game/wonRound.png"),
  voteNow: require("./images/game/voteNow1.png"),
  voteNow2: require("./images/game/voteNow2.png"),
  voteNow3: require("./images/game/voteNow3.png"),
  voteNow4: require("./images/game/voteNow4.png"),
  voteNow5: require("./images/game/voteNow5.png"),
  voteMark: require("./images/game/voteMark.png"),
  voteMark_bg: require("./images/game/voteMark_bg.png"),
  voteMark_fr: require("./images/game/voteMark_fr.png"),
  voteMark_es: require("./images/game/voteMark_es.png"),
};

export const loaderFrames = {
  frame01: require("./images/game/dubaitest.png"),
  frame02: require("./images/game/dubaitest5.png"),
  frame03: require("./images/game/dubaitest2.png"),
  frame04: require("./images/game/dubaitest6.png"),
  frame05: require("./images/game/dubaitest3.png"),
  frame06: require("./images/game/dubaitest7.png"),
  frame07: require("./images/game/dubaitest4.png"),
  frame08: require("./images/game/dubaitest8.png"),
};

export const htp_images = {
  htp01: require("./images/htp/htp01.png"),
  htp02: require("./images/htp/htp02.png"),
  htp03: require("./images/htp/htp03.png"),
  htp04: require("./images/htp/htp04.png"),
  htp05: require("./images/htp/htp05.png"),
  htp06: require("./images/htp/htp06.png"),
  htp07: require("./images/htp/htp07.png"),
  htp08: require("./images/htp/htp08.png"),
  htp09: require("./images/htp/htp09.png"),
  htp10: require("./images/htp/htp10.png"),
};

export const store_images = {
  spookyPack: require("./images/store/spooky-pack.png"),
  christmasPack: require("./images/store/christmasPack.png"),
  rosterBundle: require("./images/store/rosterBundle.png"),
  girlBundle: require("./images/store/girl-bundle.png"),
};

export const achievement_images = {
  achievement01: require("./images/achievements/ach01.png"),
  achievement02: require("./images/achievements/ach02.png"),
  achievement03: require("./images/achievements/ach03.png"),
};
